version: '2.5.{build}'

# branches to build
branches:
  # whitelist
  only:
    - master

image:
- Visual Studio 2019

environment:
  matrix:
    - platform: x64
      configuration: Debug
      platform_name: Windows

    - platform: x64
      configuration: Release
      platform_name: Windows

# clone directory
clone_folder: c:\projects\DiligentSamples

install:
  # clone submodules
  - git submodule update --init --recursive
  - git clone https://github.com/DiligentGraphics/DiligentCore.git ../DiligentCore --recursive
  - git clone https://github.com/DiligentGraphics/DiligentTools.git ../DiligentTools --recursive
  - git clone https://github.com/DiligentGraphics/DiligentFX.git ../DiligentFX --recursive
  - ps: ..\DiligentCore\BuildTools\Scripts\appveyor\install.ps1

before_build:
  - cd c:\projects\DiligentSamples\BuildTools\FormatValidation
  - validate_format_win.bat
  - cd c:\projects
  - echo cmake_minimum_required(VERSION 3.6) > CMakeLists.txt
  - echo Project(DiligentSamples_Test) >> CMakeLists.txt
  - echo add_subdirectory(DiligentCore) >> CMakeLists.txt
  - echo add_subdirectory(DiligentTools) >> CMakeLists.txt
  - echo add_subdirectory(DiligentFX) >> CMakeLists.txt
  - echo add_subdirectory(DiligentSamples) >> CMakeLists.txt
  - echo %PLATFORM%
  - cmake -S . -B ./build -G "Visual Studio 16 2019" -A %PLATFORM%
  - nuget restore c:\projects\build\DiligentSamples_Test.sln

build:
  project: c:\projects\build\DiligentSamples_Test.sln
  verbosity: minimal
  parallel: true
